name: Create Devcontainer

on:
    workflow_dispatch:
    push:
        branches:
        - main

jobs:
    build_devcontainer:
        strategy:
            matrix:
                variant: [ubuntu-24.04]
        runs-on: ubuntu-24.04
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            version: v0.16.1
            platforms: linux/amd64
            install: true
            use: true
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            build-args: VARIANT=${{ matrix.variant }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            push: true
            tags: ghcr.io/${{ github.repository }}:${{matrix.variant}}
            github-token: ${{ secrets.GITHUB_TOKEN }}
        # - name: Build Docker image
        #   run: |
        #     docker buildx build --cache-to type=gha --cache-from type=gha --push --build-arg VARIANT="${{matrix.variant}}" --platform linux/amd64 -t "ghcr.io/${{ github.repository }}:${{matrix.variant}}" .
        #   env:

        # - name: Push Docker image
        #   run: |
        #     docker push "ghcr.io/${{ github.repository }}:${{matrix.variant}}"

